language: rust
rust: nightly-2019-06-20
cache:
  - cargo: true
  - directories:
    - backend/target
    - node_modules
    - "$TRAVIS_HOME/.npm"
    - "$TRAVIS_HOME/.nvm"


# Install same version of wasm-bindgen-cli as of wasm-bindgen in Cargo.lock
INSTALL_WASM_BINDGEN_CLI: &INSTALL_WASM_BINDGEN_CLI
  |
    wanted_version=$(sed -n '/^name = "wasm-bindgen"$/{N;s/.*\nversion = "\(.*\)"$/\1/p}' backend/Cargo.lock)
    if ! which wasm-bindgen &>/dev/null; then
      should_install=true
    else
      current_version=$(wasm-bindgen --version | cut -d' ' -f2)
      if [ "$wanted_version" != "$current_version" ]; then
        should_install=true
      fi
    fi
    if [ -n "$should_install" ]; then
      cargo install --version "$wanted_version" wasm-bindgen-cli
    fi

install:
  - nvm install v10.13
  - *INSTALL_WASM_BINDGEN_CLI
  - make dependencies


script:
  - set -e
  - make test
  - make release


deploy:
  - provider: script
    script: >
      npm install netlify-cli -g &&
      netlify deploy
      --site "$NETLIFY_SITE_ID"
      --auth "$NETLIFY_ACCESS_TOKEN"
      --message "${TRAVIS_BRANCH} @${TRAVIS_COMMIT}: $TRAVIS_COMMIT_MESSAGE"
      --dir dist # Keep this comment here; Travis CI appends an n otherwise
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master

  - provider: script
    script: >
      npm install netlify-cli -g &&
      netlify deploy --prod
      --site "$NETLIFY_SITE_ID"
      --auth "$NETLIFY_ACCESS_TOKEN"
      --message "${TRAVIS_BRANCH} @${TRAVIS_COMMIT}: $TRAVIS_COMMIT_MESSAGE"
      --dir dist # Keep this comment here; Travis CI appends an n otherwise
    skip_cleanup: true

  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: dist
    skip_cleanup: true
