[package]
name = "eva-web"
version = "0.1.0"
authors = ["Stijn Seghers <stijnseghers@gmail.com>"]
edition = "2018"

[lib]
name = "eva"
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
console_error_panic_hook = "0.1"
error-chain = "0.12"
futures-preview = { version = "=0.3.0-alpha.13", features = ["compat"] }
js-sys = "0.3"
rand = { version = "0.6", features = ["wasm-bindgen"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.3"
web-sys = { version = "0.3", features = ["console"] }

[dependencies.eva]
git = "https://github.com/Procrat/eva"
rev = "6d1074e"
default-features = false
