[package]
name = "eva-web"
version = "0.1.0"
authors = ["Stijn Seghers <stijnseghers@gmail.com>"]
edition = "2018"

[lib]
name = "eva"
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
console_error_panic_hook = "0.1"
derive_more = "0.15"
failure = "0.1"
futures-preview = { version = "=0.3.0-alpha.16" }
js-sys = "0.3"
rand = { version = "0.6", features = ["wasm-bindgen"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.3", features = ["futures_0_3"] }
web-sys = { version = "0.3", features = ["console"] }

[dependencies.eva]
git = "https://github.com/Procrat/eva"
rev = "026a1519a9a61addd6dd1828410ec3ffed5428c2"
default-features = false
